spring:
  application:
    name: ${application.name}
  profiles:
    active: noauth
  main:
    web-environment: true
    web-application-type: servlet
    allow-bean-definition-overriding: true

server:
  port: 8080

camel:
  component:
    servlet:
      mapping:
        context-path: /${cacher.name}/api/v1/*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
    fetch-registry: false
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

cache:
  baseurl: /${cacher.name}/api/v1
  api:
    port: 8081